### ISSUE TITLE
pep8-naming should not warning for lowercase methods name on unittest children classes

### ISSUE THREAD

**Issue by elyezer** [flintwork/pep8-naming#18] opened 2015-02-09 18:00 UTC
I run flake8 every time a PR is sent to the repository and for every test class which override, for example, `setUp` or `tearDown` methods I have to add `noqa` to that line.

Even Python 3 uses that convention for unittest inherited classes.

**Comment by sigmavirus24** [comment] 2015-02-09 23:03
Duplicate of #6

**Closed by sigmavirus24** 2015-02-09 23:03 UTC

**Comment by elyezer** [comment] 2015-02-09 23:08
Sorry missed that.
